import components from "@/components";
import { Achievements } from "@/components/section/about/achievements";
import { Ourtasks } from "@/components/section/about/OurTasks";

import Head from "next/head";

export default function About() {
  const commonComp = components.common;
  return (
    <>
      <Head>
        <title>ABSOLUTE ENERGY</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <commonComp.PageHeader
          title="О НАС"
          description="Информация о нашей компании, нашей деятельности и услуг"
        />
        <Achievements />
        <Ourtasks />
      </main>
    </>
  );
}
