import components from "@/components";
import { PortifolioServices } from "@/components/section/services/portifolio";
import { ServicesHero } from "@/components/section/services/services-hero";

import Head from "next/head";

export default function Services() {
  const commonComp = components.common;
  return (
    <>
      <Head>
        <title>ABSOLUTE ENERGY</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <commonComp.PageHeader
          title="Основные направления"
          description="Исследуйте современные тенденции и перспективы развития, чтобы получить полное понимание ключевых аспектов и направлений, влияющих на вашу сферу интересов."
        />
        <ServicesHero />
        <PortifolioServices />
      </main>
    </>
  );
}
